### ISSUE TITLE
Enhancement : Add a requirement.txt file or use pipenv package manager to handle dependency

### ISSUE THREAD

**Issue by manoj9896** [Ctoic/Hostel-Management-System-Using-Flask#13]
Including a `requirements.txt` file or adopting a tool like `pipenv` improves clarity and makes it easier for other developers to set up the environment, install necessary dependencies, and contribute to the project. It helps ensure consistency across different setups, which is essential for collaboration.
It improves reproducibility, reduces onboarding time for new developers, and makes the project easier to maintain in the long term.

**Comment by manoj9896** [comment]
@Ctoic would like to work on this issue as well

**Comment by Ctoic** [comment]
Sure @manoj9896
