### ISSUE TITLE
Admin Registration Not Storing Data in Database

### ISSUE THREAD

**Issue by Ctoic** [Ctoic/Hostel-Management-System-Using-Flask#21]
**Bug: Admin Registration Fails to Store Data in Database**

Description:
The admin registration functionality does not store the admin's information in the database. When attempting to register a new admin, no errors are thrown during the registration process, but the data is not committed to the database. This issue needs to be investigated and resolved.

Steps to Reproduce:
Navigate to the /admin_register route.
Fill in the required fields (name, email, and password) in the registration form.
Submit the form.
Check the database (e.g., using SQLite viewer or MySQL command line) to confirm that the admin's information is not stored.
Expected Behavior:
The admin's details should be saved in the database after successful form submission.
A success message should be displayed, and the admin should be redirected to the login page.
Actual Behavior:
The success message appears, and the redirection works, but the admin's information is missing from the database.
Possible Causes:
The generate_password_hash function might not be working as expected, causing the registration to fail.
The database session may not be committing properly due to transaction rollback.
Database model definition issues, such as incorrect field names or missing attributes.
Incorrect configuration or connection issues with the database (e.g., SQLite setup in Flask).
Suggested Debugging Steps:
Check the logs to see if any errors or exceptions are being caught during the registration process.
Verify that the Admin model's fields match the form data and are correctly defined.
Test if a manual database entry using SQLAlchemy commands works without the form submission.
Ensure that the db.session.commit() statement is correctly executed without errors.
Additional Information:
Database: SQLite (sqlite:///hostel.db)
Flask Extensions: SQLAlchemy, Flask-Migrate, Flask-Bcrypt
Endpoint: /admin_register
Acceptance Criteria:
 Admin information is successfully stored in the database after registration.
 Error handling is in place for cases where registration fails.
 Logs show clear information when the database transaction is committed successfully.

**Comment by aliabbasnagari** [comment]
Assign

**Comment by Ctoic** [comment]
After Contributions from couple of devs it's not working as expected. I have 2 more projects to maintain it will be great help if you solve these bugs.

**Comment by aliabbasnagari** [comment]
Fixed this issue and created pull request

**Comment by Ctoic** [comment]
Great @aliabbasnagari 🚀
